name = "Icepack"
author = "Vinicius Santos"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12bd9daff323428c7a1ef6aff4f3916d83e3d9429b5041cd19a869ab47b64ae5"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"
